apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: wget-taskrun-
spec:
  params:
  - name: url
    value: www.google.com
  - name: diroptions
    value:
    - -P
  taskRef:
    kind: Task
    name: wget
  workspaces:
  - emptyDir: {}
    name: wget-workspace