apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: Code Quality
    tekton.dev/displayName: YAML linter
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: linter
  creationTimestamp: "2021-09-30T17:27:23Z"
  generation: 1
  labels:
    app.kubernetes.io/version: "0.1"
    hub.tekton.dev/catalog: tekton
  managedFields:
  - apiVersion: tekton.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:tekton.dev/categories: {}
          f:tekton.dev/displayName: {}
          f:tekton.dev/pipelines.minVersion: {}
          f:tekton.dev/tags: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/version: {}
          f:hub.tekton.dev/catalog: {}
      f:spec:
        .: {}
        f:description: {}
        f:params: {}
        f:steps: {}
        f:workspaces: {}
    manager: tkn
    operation: Update
    time: "2021-09-30T17:27:22Z"
  name: yaml-lint
  namespace: christopher-ley-pipeline-assignment
  resourceVersion: "5641594"
  selfLink: /apis/tekton.dev/v1beta1/namespaces/christopher-ley-pipeline-assignment/tasks/yaml-lint
  uid: 8c6290a4-cdb3-41ea-aa5e-1e1f1cfc7ece
spec:
  description: This task can be used to perform lint check on YAML files
  params:
  - default:
    - --help
    description: extra args needs to append
    name: args
    type: array
  steps:
  - args:
    - $(params.args)
    command:
    - yamllint
    image: docker.io/cytopia/yamllint:1.23@sha256:e9deea51bbdc35950cacf6594dab94100d9bbf5c987540b8874167d58e6bdce2
    name: lint-yaml-files
    resources: {}
    workingDir: $(workspaces.shared-workspace.path)
  workspaces:
  - description: A workspace that contains the fetched git repository.
    name: shared-workspace
