apiVersion: v1
imagePullSecrets:
- name: pipeline-dockercfg-p5xmn
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-09-30T17:27:14Z"
  name: pipeline
  namespace: christopher-ley-pipeline-assignment
  resourceVersion: "5641517"
  selfLink: /api/v1/namespaces/christopher-ley-pipeline-assignment/serviceaccounts/pipeline
  uid: 5083a635-d3fc-4ae6-a121-7996e948bc40
secrets:
- name: pipeline-token-8blrw
- name: pipeline-dockercfg-p5xmn
